#! /usr/bin/python

import subprocess
import webbrowser
import sys
import json
from pprint import pprint

json_file = 'projectstart.json'

def openInBrowser( url ):
    ""
    if sys.platform == 'darwin':
        subprocess.Popen(['open',url])
    else:
        webbrowser.open_new_tab(url)

with open(json_file) as data_file:
    data = json.load(data_file)

for url in data['urls']:
    openInBrowser(url)

